//Vox prefs and sprite accessories
GLOBAL_LIST_EMPTY(vox_quills_list)
GLOBAL_LIST_EMPTY(vox_facial_quills_list)
GLOBAL_LIST_EMPTY(vox_tails_list)
GLOBAL_LIST_EMPTY(vox_body_markings_list)
GLOBAL_LIST_EMPTY(vox_tail_markings_list)
GLOBAL_LIST_EMPTY(animated_vox_tails_list)
GLOBAL_LIST_EMPTY(animated_vox_tail_markings_list)
