/obj/structure/closet/crate/royale/PopulateContents()
	if(prob(20))
		new /obj/item/ammo_box/magazine/m12g(src)
		new /obj/item/ammo_box/magazine/m12g(src)
		new /obj/item/gun/ballistic/automatic/shotgun/bulldog(src)
		new /obj/item/clothing/suit/armor/riot(src)

	else if(prob(25))
		new /obj/item/clothing/suit/fire/firefighter(src)
		new /obj/item/clothing/mask/gas(src)
		new /obj/item/tank/internals/oxygen/red(src)
		new /obj/item/extinguisher(src)
		new /obj/item/clothing/head/hardhat/red(src)
		new /obj/item/flamethrower/full/tank(src)

	else if(prob(33))
		new /obj/item/gun/ballistic/revolver/mateba(src)
		new /obj/item/ammo_box/a357(src)
		new /obj/item/clothing/suit/armor/bulletproof(src)
		new /obj/item/melee/classic_baton/telescopic(src)

	else if(prob(50))
		new /obj/item/gun/energy/e_gun(src)
		new /obj/item/gun/energy/e_gun/advtaser(src)
		new /obj/item/clothing/head/helmet(src)

	else
		new /obj/item/reagent_containers/spray/waterflower/lube(src)
		new /obj/item/soap/syndie(src)
		new /obj/item/clothing/shoes/chameleon/noslip(src)
		new /obj/item/clothing/mask/gas/clown_hat(src)