/obj/structure/closet/crate/sphere
	desc = "An Advanced Crate that defies all known cargo standards."
	name = "Advanced Crate"
	icon = 'yogstation/icons/obj/crates.dmi'
	icon_state = "round"

/obj/structure/closet/crate/large/goats
	name = "goat crate"
	desc = "Contains a completly random goat from Goat Tech Industries that may or may not break the laws of science!"

/obj/structure/closet/crate/large/goats/Initialize()
		var/loot = rand(1,26) //26 different goats!
	switch(loot)
		if(1)
			new /mob/living/simple_animal/hostile/retaliate/goat(src)
		if(2)
			new /mob/living/simple_animal/hostile/retaliate/goat/clown(src)
		if(3)
			new /mob/living/simple_animal/hostile/retaliate/goat/ras(src)
		if(4)
			new /mob/living/simple_animal/hostile/retaliate/goat/blue(src)
		if(5)
			new /mob/living/simple_animal/hostile/retaliate/goat/chocolate(src)
		if(6)
			new /mob/living/simple_animal/hostile/retaliate/goat/christmas(src)
		if(7)
			new /mob/living/simple_animal/hostile/retaliate/goat/confetti(src)
		if(8)
			new /mob/living/simple_animal/hostile/retaliate/goat/cottoncandy(src)
		if(9)
			new /mob/living/simple_animal/hostile/retaliate/goat/glowing(src)
		if(10)
			new /mob/living/simple_animal/hostile/retaliate/goat/goatgoat(src)
		if(11)
			new /mob/living/simple_animal/hostile/retaliate/goat/horror(src)
		if(12)
			new /mob/living/simple_animal/hostile/retaliate/goat/inverted(src)
		if(13)
			new /mob/living/simple_animal/hostile/retaliate/goat/memory(src)
		if(14)
			new /mob/living/simple_animal/hostile/retaliate/goat/mirrored(src)
		if(15)
			new /mob/living/simple_animal/hostile/retaliate/goat/paper(src)
		if(16)
			new /mob/living/simple_animal/hostile/retaliate/goat/pixel(src)
		if(17)
			new /mob/living/simple_animal/hostile/retaliate/goat/radioactive(src)
		if(18)
			new /mob/living/simple_animal/hostile/retaliate/goat/rainbow(src)
		if(19)
			new /mob/living/simple_animal/hostile/retaliate/goat/spiffles(src)
		if(20)
			new /mob/living/simple_animal/hostile/retaliate/goat/star(src)
		if(21)
			new /mob/living/simple_animal/hostile/retaliate/goat/twisted(src)
		if(22)
			new /mob/living/simple_animal/hostile/retaliate/goat/huge(src)
		if(23)
			new /mob/living/simple_animal/hostile/retaliate/goat/tiny(src)
		if(24)
			new /mob/living/simple_animal/hostile/retaliate/goat/ghost(src)
		if(25)
			new /mob/living/simple_animal/hostile/retaliate/goat/brick(src)
		if(26)
			new /mob/living/simple_animal/hostile/retaliate/goat/watercolor(src)