/obj/structure/closet/crate/sphere
	desc = "An Advanced Crate that defies all known cargo standards."
	name = "Advanced Crate"
	icon = 'yogstation/icons/obj/crates.dmi'
	icon_state = "round"

/obj/structure/closet/crate/critter/exoticgoats
	name = "goat crate"
	desc = "Contains a completly random goat from Goat Tech Industries that may or may not break the laws of science!"

/obj/structure/closet/crate/critter/exoticgoats/Initialize()
	var/loot = rand(1,39) //39 different goats!
	switch(loot)
		if(1)
			new /mob/living/simple_animal/hostile/retaliate/goat(loc)
		if(2)
			new /mob/living/simple_animal/hostile/retaliate/goat/clown(loc)
		if(3)
			new /mob/living/simple_animal/hostile/retaliate/goat/ras(loc)
		if(4)
			new /mob/living/simple_animal/hostile/retaliate/goat/blue(loc)
		if(5)
			new /mob/living/simple_animal/hostile/retaliate/goat/chocolate(loc)
		if(6)
			new /mob/living/simple_animal/hostile/retaliate/goat/christmas(loc)
		if(7)
			new /mob/living/simple_animal/hostile/retaliate/goat/confetti(loc)
		if(8)
			new /mob/living/simple_animal/hostile/retaliate/goat/cottoncandy(loc)
		if(9)
			new /mob/living/simple_animal/hostile/retaliate/goat/glowing(loc)
		if(10)
			new /mob/living/simple_animal/hostile/retaliate/goat/goatgoat(loc)
		if(11)
			new /mob/living/simple_animal/hostile/retaliate/goat/horror(loc)
		if(12)
			new /mob/living/simple_animal/hostile/retaliate/goat/inverted(loc)
		if(13)
			new /mob/living/simple_animal/hostile/retaliate/goat/memory(loc)
		if(14)
			new /mob/living/simple_animal/hostile/retaliate/goat/mirrored(loc)
		if(15)
			new /mob/living/simple_animal/hostile/retaliate/goat/paper(loc)
		if(16)
			new /mob/living/simple_animal/hostile/retaliate/goat/pixel(loc)
		if(17)
			new /mob/living/simple_animal/hostile/retaliate/goat/radioactive(loc)
		if(18)
			new /mob/living/simple_animal/hostile/retaliate/goat/rainbow(loc)
		if(19)
			new /mob/living/simple_animal/hostile/retaliate/goat/spiffles(loc)
		if(20)
			new /mob/living/simple_animal/hostile/retaliate/goat/star(loc)
		if(21)
			new /mob/living/simple_animal/hostile/retaliate/goat/twisted(loc)
		if(22)
			new /mob/living/simple_animal/hostile/retaliate/goat/huge(loc)
		if(23)
			new /mob/living/simple_animal/hostile/retaliate/goat/tiny(loc)
		if(24)
			new /mob/living/simple_animal/hostile/retaliate/goat/ghost(loc)
		if(25)
			new /mob/living/simple_animal/hostile/retaliate/goat/brick(loc)
		if(26)
			new /mob/living/simple_animal/hostile/retaliate/goat/watercolor(loc)
		if(27)
			new /mob/living/simple_animal/hostile/retaliate/goat/brown(loc)
		if(28)
			new /mob/living/simple_animal/hostile/retaliate/goat/panda(loc)
		if(29)
			new /mob/living/simple_animal/hostile/retaliate/goat/black(loc)
		if(30)
			new /mob/living/simple_animal/hostile/retaliate/goat/green(loc)
		if(31)
			new /mob/living/simple_animal/hostile/retaliate/goat/orange(loc)
		if(32)
			new /mob/living/simple_animal/hostile/retaliate/goat/purple(loc)
		if(33)
			new /mob/living/simple_animal/hostile/retaliate/goat/red(loc)
		if(34)
			new /mob/living/simple_animal/hostile/retaliate/goat/yellow(loc)
		if(35)
			new /mob/living/simple_animal/hostile/retaliate/goat/legitgoat(loc)
		if(36)
			new /mob/living/simple_animal/hostile/retaliate/goat/skiddo(loc)
		if(37)
			new /mob/living/simple_animal/hostile/retaliate/goat/gogoat(loc)
		if(38)
			new /mob/living/simple_animal/hostile/retaliate/goat/sanic(loc)
		if(39)
			new /mob/living/simple_animal/hostile/retaliate/goat/plunger(loc)