/obj/structure/closet/secure_closet/captains/PopulateContents()
	..()
	new /obj/item/radio/security(src)

/obj/structure/closet/secure_closet/hos/PopulateContents()
	..()
	new /obj/item/radio/security(src)

/obj/structure/closet/secure_closet/warden/PopulateContents()
	..()
	new /obj/item/radio/security(src)

/obj/structure/closet/secure_closet/security/PopulateContents()
	..()
	new /obj/item/radio/security(src)
	new /obj/item/clipboard/yog/paperwork/security(src)

/obj/structure/closet/secure_closet/detective/PopulateContents()
	..()
	new /obj/item/clothing/under/yogs/forensictech(src)
	new /obj/item/clothing/under/yogs/bluedetective(src)
	new /obj/item/clothing/under/yogs/golddetective(src)
	new /obj/item/clothing/under/yogs/greydetective(src)
	new /obj/item/clothing/under/yogs/blackdetective(src)
	new /obj/item/clothing/suit/yogs/golddetective(src)
	new /obj/item/clothing/suit/yogs/detectivecoat(src)
	new /obj/item/clothing/suit/yogs/bluedetective(src)