var/list/donor_start_items = list(\
						/obj/item/clothing/head/yogs/beanie, \
						/obj/item/clothing/head/yogs/bike, \
						/obj/item/clothing/head/yogs/hardsuit_helm_clown, \
						/obj/item/clothing/head/yogs/cowboy, \
						/obj/item/clothing/head/yogs/crusader, \
						/obj/item/clothing/head/yogs/cowboy_sheriff, \
						/obj/item/clothing/head/yogs/dallas, \
						/obj/item/clothing/head/yogs/drinking_hat, \
						/obj/item/clothing/head/yogs/microwave, \
						/obj/item/clothing/head/yogs/sith_hood, \
						/obj/item/clothing/head/yogs/turban, \
						/obj/item/clothing/head/collectable/petehat, \
						/obj/item/clothing/head/collectable/slime, \
						/obj/item/clothing/head/collectable/xenom, \
						/obj/item/clothing/head/collectable/chef, \
						/obj/item/clothing/head/collectable/paper, \
						/obj/item/clothing/head/collectable/tophat, \
						/obj/item/clothing/head/collectable/captain, \
						/obj/item/clothing/head/collectable/police, \
						/obj/item/clothing/head/collectable/welding, \
						/obj/item/clothing/head/collectable/flatcap, \
						/obj/item/clothing/head/collectable/pirate, \
						/obj/item/clothing/head/collectable/kitty, \
						/obj/item/clothing/head/collectable/rabbitears, \
						/obj/item/clothing/head/collectable/wizard, \
						/obj/item/clothing/head/collectable/hardhat, \
						/obj/item/clothing/head/collectable/HoS, \
						/obj/item/clothing/head/collectable/thunderdome, \
						/obj/item/clothing/head/collectable/swat, \
						/obj/item/clothing/head/hardhat/cakehat, \
						/obj/item/clothing/head/ushanka, \
						/obj/item/clothing/head/hardhat/pumpkinhead, \
						/obj/item/clothing/head/kitty, \
						/obj/item/clothing/head/hardhat/reindeer, \
						/obj/item/clothing/head/powdered_wig, \
						/obj/item/clothing/head/that, \
						/obj/item/clothing/head/redcoat, \
						/obj/item/clothing/head/mailman, \
						/obj/item/clothing/head/plaguedoctorhat, \
						/obj/item/clothing/head/hasturhood, \
						/obj/item/clothing/head/nursehat, \
						/obj/item/clothing/head/cardborg, \
						/obj/item/clothing/head/justice, \
						/obj/item/clothing/head/rabbitears, \
						/obj/item/clothing/head/flatcap, \
						/obj/item/clothing/head/pirate, \
						/obj/item/clothing/head/bowler, \
						/obj/item/clothing/head/witchwig, \
						/obj/item/clothing/head/chicken, \
						/obj/item/clothing/head/fedora, \
						/obj/item/clothing/head/sombrero, \
						/obj/item/clothing/head/sombrero/green, \
						/obj/item/clothing/head/cone, \
						/obj/item/clothing/head/collectable/beret, \
						/obj/item/clothing/head/crown, \
						/obj/item/clothing/head/wizard/marisa/fake, \
						/obj/item/clothing/neck/yogs/sith_cloak, \
						/obj/item/clothing/suit/yogs/armor/sith_suit, \
						/obj/item/clothing/suit/yogs/armor/hardsuit_clown, \
						/obj/item/clothing/shoes/yogs/trainers, \
						/obj/item/clothing/shoes/yogs/trainers/red, \
						/obj/item/clothing/shoes/yogs/trainers/white, \
						/obj/item/clothing/shoes/yogs/trainers/zebra, \
						/obj/item/clothing/shoes/yogs/trainers/darkbrown, \
						/obj/item/clothing/shoes/yogs/trainers/black, \
						/obj/item/clothing/suit/yogs/zebrasweat, \
						/obj/item/clothing/suit/yogs/blackwhitesweat, \
						/obj/item/clothing/shoes/yogs/fuzzy_slippers
						)

var/list/donor_pdas = list("Normal", "Transparent", "Pip Boy", "Rainbow")
