var/list/donor_start_items = list(\
						/obj/item/clothing/head/yogs/beanie, \
						/obj/item/clothing/head/yogs/bike, \
						/obj/item/clothing/head/yogs/hardsuit_helm_clown, \
						/obj/item/clothing/head/yogs/cowboy, \
						/obj/item/clothing/head/yogs/crusader, \
						/obj/item/clothing/head/yogs/cowboy_sheriff, \
						/obj/item/clothing/head/yogs/dallas, \
						/obj/item/clothing/head/yogs/drinking_hat, \
						/obj/item/clothing/head/yogs/microwave, \
						/obj/item/clothing/head/yogs/sith_hood, \
						/obj/item/clothing/head/yogs/turban, \
						/obj/item/clothing/head/collectable/petehat, \
						/obj/item/clothing/head/collectable/slime, \
						/obj/item/clothing/head/collectable/xenom, \
						/obj/item/clothing/head/collectable/chef, \
						/obj/item/clothing/head/collectable/paper, \
						/obj/item/clothing/head/collectable/tophat, \
						/obj/item/clothing/head/collectable/captain, \
						/obj/item/clothing/head/collectable/police, \
						/obj/item/clothing/head/collectable/welding, \
						/obj/item/clothing/head/collectable/flatcap, \
						/obj/item/clothing/head/collectable/pirate, \
						/obj/item/clothing/head/collectable/kitty, \
						/obj/item/clothing/head/collectable/rabbitears, \
						/obj/item/clothing/head/collectable/wizard, \
						/obj/item/clothing/head/collectable/hardhat, \
						/obj/item/clothing/head/collectable/HoS, \
						/obj/item/clothing/head/collectable/thunderdome, \
						/obj/item/clothing/head/collectable/swat, \
						/obj/item/clothing/head/ushanka, \
						/obj/item/clothing/head/hardhat/pumpkinhead, \
						/obj/item/clothing/head/kitty, \
						/obj/item/clothing/head/hardhat/reindeer, \
						/obj/item/clothing/head/powdered_wig, \
						/obj/item/clothing/head/that, \
						/obj/item/clothing/head/redcoat, \
						/obj/item/clothing/head/mailman, \
						/obj/item/clothing/head/plaguedoctorhat, \
						/obj/item/clothing/head/hasturhood, \
						/obj/item/clothing/head/nursehat, \
						/obj/item/clothing/head/cardborg, \
						/obj/item/clothing/head/justice, \
						/obj/item/clothing/head/rabbitears, \
						/obj/item/clothing/head/flatcap, \
						/obj/item/clothing/head/pirate, \
						/obj/item/clothing/head/bowler, \
						/obj/item/clothing/head/witchwig, \
						/obj/item/clothing/head/chicken, \
						/obj/item/clothing/head/fedora, \
						/obj/item/clothing/head/sombrero, \
						/obj/item/clothing/head/sombrero/green, \
						/obj/item/clothing/head/cone, \
						/obj/item/clothing/head/collectable/beret, \
						/obj/item/clothing/head/crown, \
						/obj/item/clothing/head/wizard/fake/red, \
						/obj/item/clothing/head/wizard/fake/yellow, \
						/obj/item/clothing/head/wizard/fake/black, \
						/obj/item/clothing/head/wizard/marisa/fake
						)

var/list/donor_pdas = list("Normal", "Transparent", "Pip Boy", "Rainbow")

var/list/donor_start_tools = list(\
						/obj/item/storage/backpack/snail/green, \
						/obj/item/banhammer, \
						/obj/item/bedsheet/cosmos, \
						/obj/item/bedsheet/wiz, \
						/obj/item/bedsheet/cult, \
						/obj/item/bedsheet/nanotrasen, \
						/obj/item/bedsheet/centcom, \
						/obj/item/bedsheet/syndie, \
						/obj/item/bikehorn/airhorn, \
						/obj/item/camera, \
						/obj/item/cane, \
						/obj/item/clothing/shoes/sneakers/rainbow, \
						/obj/item/clothing/gloves/color/rainbow, \
						/obj/item/clothing/under/color/rainbow, \
						/obj/item/clothing/neck/yogs/sith_cloak, \
						/obj/item/clothing/suit/yogs/armor/sith_suit, \
						/obj/item/clothing/suit/yogs/armor/hardsuit_clown, \
						/obj/item/clothing/shoes/yogs/trainers, \
						/obj/item/clothing/shoes/yogs/trainers/red, \
						/obj/item/clothing/shoes/yogs/trainers/white, \
						/obj/item/clothing/shoes/yogs/trainers/zebra, \
						/obj/item/clothing/shoes/yogs/trainers/darkbrown, \
						/obj/item/clothing/shoes/yogs/trainers/black, \
						/obj/item/clothing/suit/yogs/zebrasweat, \
						/obj/item/clothing/suit/yogs/blackwhitesweat, \
						/obj/item/clothing/shoes/yogs/fuzzy_slippers, \
						/obj/item/clothing/suit/xenos, \
						/obj/item/grown/sunflower, \
						/obj/item/hot_potato/harmless/toy, \
						/obj/item/instrument/accordion, \
						/obj/item/instrument/glockenspiel, \
						/obj/item/instrument/harmonica, \
						/obj/item/instrument/recorder, \
						/obj/item/instrument/saxophone, \
						/obj/item/latexballon, \
						/obj/item/lighter, \
						/obj/item/lipstick/random, \
						/obj/item/poster/random_contraband, \
						/obj/item/poster/random_official, \
						/obj/item/razor, \
						/obj/item/toy/balloon, \
						/obj/item/toy/beach_ball, \
						/obj/item/toy/clockwork_watch, \
						/obj/item/toy/dummy, \
						/obj/item/toy/eightball, \
						/obj/item/toy/katana, \
						/obj/item/toy/gun, \
						/obj/item/toy/plush/plushvar, \
						/obj/item/toy/plush/narplush, \
						/obj/item/toy/sword
						)
