#define is_thrall(M) (istype(M, /mob/living) && M.mind && M.mind.has_antag_datum(/datum/antagonist/thrall))
#define is_sling(M) (istype(M, /mob/living) && M.mind && M.mind.has_antag_datum(/datum/antagonist/shadowling))
#define is_sling_or_thrall(M) (is_thrall(M) || is_sling(M))
#define isshadow(A) (is_species(A, /datum/species/shadow))
#define isshadowling(A) (is_species(A, /datum/species/shadow/ling))
#define isborer(A) (istype(A, /mob/living/simple_animal/borer))
#define iscaptive(A) (istype(A, /mob/living/captive_brain))