/obj/structure/closet/crate/battleroyale
	name = "Supply Crate"
	icon_state = "miningcar"
	light_range = 10
	light_color = LIGHT_COLOR_YELLOW //Let it glow, let it glow

/obj/structure/closet/crate/battleroyale/PopulateContents()
	. = ..()
	if(prob(50)) //Weapons crate
		if(prob(30)) //Common
			var/num = rand(1,6)
			switch(num)
				if(1)
					new /obj/item/circular_saw(src)
				if(2)
					new /obj/item/kitchen/knife/combat/survival(src)
				if(3)
					new /obj/item/pen/edagger(src)
				if(4)
					new /obj/item/grenade/plastic/c4(src)
				if(5)
					new /obj/item/gun/ballistic/automatic/toy/pistol/riot(src)
				if(6)
					new /obj/item/gun/ballistic/revolver/doublebarrel/improvised(src)
		else if(prob(30))
			var/num = rand(1,8)
			switch(num)
				if(1)
					new /obj/item/flamethrower/full/tank(src)
				if(2)
					new /obj/item/gun/ballistic/shotgun/automatic/combat(src)
				if(3)
					new /obj/item/gun/ballistic/automatic/pistol(src)
				if(4)
					new /obj/item/melee/transforming/energy/sword(src)
				if(5)
					new /obj/item/gun/ballistic/revolver/doublebarrel(src)
				if(6)
					new /obj/item/gun/energy/laser/retro/old(src)
				if(7)
					new /obj/item/storage/box/syndie_kit/throwing_weapons(src)
				if(8)
					new /obj/item/gun/energy/wormhole_projector(src)
		else if(prob(25))
			var/num = rand(1,8)
			switch(num)
				if(1)
					new /obj/item/gun/energy/laser(src)
				if(2)
					new /obj/item/gun/ballistic/automatic/wt550(src)
				if(3)
					new /obj/item/grenade/syndieminibomb(src)
				if(4)
					new /obj/item/storage/backpack/duffelbag/syndie/c4(src)
				if(5)
					new /obj/item/gun/ballistic/automatic/c20r/toy/unrestricted/riot(src)
				if(6)
					new /obj/item/gun/ballistic/shotgun/riot(src)
				if(7)
					new /obj/item/gun/ballistic/revolver/detective(src)
				if(8)
					new /obj/item/gun/ballistic/automatic/pistol/suppressed(src)
		else if(prob(10))
			var/num = rand(1,8)
			switch(num)
				if(1)
					new /obj/item/gun/ballistic/shotgun/automatic/combat/compact(src)
				if(2)
					new /obj/item/gun/ballistic/revolver(src)
				if(3)
					new /obj/item/gun/ballistic/automatic/pistol/deagle(src)
				if(4)
					new /obj/machinery/syndicatebomb(src)
				if(5)
					new /obj/item/shield/energy(src)
				if(6)
					new /obj/item/gun/ballistic/automatic/l6_saw/toy/unrestricted/riot(src)
				if(7)
					new /obj/item/gun/energy/laser/captain(src)
				if(8)
					new /obj/item/gun/ballistic/revolver/grenadelauncher/unrestricted(src)
		else //Legendary
			var/num = rand(1-10)
			switch(num)
				if(1)
					new /obj/item/gun/energy/beam_rifle(src)
				if(2)
					new /obj/item/gun/ballistic/automatic/c20r/unrestricted(src)
				if(3)
					new /obj/item/gun/ballistic/automatic/mini_uzi(src)
				if(4)
					new /obj/item/gun/ballistic/automatic/shotgun/bulldog/unrestricted(src)
				if(5)
					new /obj/item/gun/ballistic/automatic/tommygun(src)
				if(6)
					new /obj/item/gun/ballistic/shotgun/automatic/dual_tube(src)
				if(7)
					new /obj/item/gun/ballistic/rocketlauncher/unrestricted(src)
				if(8)
					new /obj/item/gun/ballistic/automatic/sniper_rifle(src)
				if(9)
					new /obj/item/gun/ballistic/automatic/ar(src)
				if(10)
					new /obj/item/gun/ballistic/automatic/m90/unrestricted(src)

	else //Item crate
		if(prob(30)) //Common
			new /obj/item/storage/firstaid(src)
			new /obj/item/ammo_box/a357(src)
			new /obj/item/ammo_box/c38(src)
			new /obj/item/clothing/suit/armor/vest(src)
			return
		else if(prob(30))
			new /obj/item/ammo_box/c9mm(src)
			new /obj/item/ammo_box/c10mm(src)
			new /obj/item/ammo_box/c45(src)
			new /obj/item/clothing/suit/armor/vest(src)
			new /obj/item/reagent_containers/hypospray/mixi(src)
			new /obj/item/storage/firstaid(src)
			new /obj/item/shield/riot(src)
			return
		else if(prob(25))
			new /obj/item/ammo_box/a40mm(src)
			new /obj/item/ammo_box/a762(src)
			new /obj/item/reagent_containers/hypospray/mixi(src)
			new /obj/item/reagent_containers/hypospray/derm(src)
			new /obj/item/storage/firstaid/fire(src)
			new /obj/item/clothing/suit/armor/riot(src)
			return
		else if(prob(10))
			new /obj/item/ammo_box/n762(src)
			new /obj/item/ammo_box/foambox/riot
			new /obj/item/clothing/suit/space/hardsuit/ert/sec(src)
			new /obj/item/storage/firstaid(src)
			new /obj/item/storage/firstaid/fire(src)
			return
		else //Legendary
			new /obj/item/ammo_box/a357(src)
			new /obj/item/ammo_box/c38(src)
			new /obj/item/ammo_box/c9mm(src)
			new /obj/item/ammo_box/c10mm(src)
			new /obj/item/ammo_box/c45(src)
			new /obj/item/ammo_box/a40mm(src)
			new /obj/item/ammo_box/a762(src)
			new /obj/item/ammo_box/n762(src)
			new /obj/item/ammo_box/foambox/riot
			new /obj/item/clothing/suit/space/hardsuit/syndi(src)
			new /obj/item/storage/firstaid(src)
			new /obj/item/storage/firstaid/toxin(src)
			return

//	new /obj/item/clipboard/yog/paperwork/hos(src)
