/datum/weather/rad_storm
	protected_areas = list(/area/station/maintenance,
							/area/station/ai_monitored/turret_protected/ai_upload, /area/station/ai_monitored/turret_protected/ai_upload_foyer,
							/area/station/ai_monitored/turret_protected/aisat/maint, /area/station/ai_monitored/command/storage/satellite,
							/area/station/ai_monitored/turret_protected/ai, /area/station/commons/storage/emergency/starboard,
							/area/station/commons/storage/emergency/port, /area/shuttle, /area/station/common/cryopods, /area/station/security/prison/safe,
							/area/station/security/prison/toilet, /area/icemoon/underground, /area/station/service/hydroponics/garden/abandoned,
							/area/station/security/detectives_office/private_investigators_office, /area/station/security/bitden,
							/area/station/service/library/abandoned, /area/station/service/theater/abandoned, /area/station/service/abandoned_gambling_den,
							/area/station/service/electronic_marketing_den, /area/station/service/kitchen/abandoned, /area/station/medical/abandoned,
							/area/station/science/research/abandoned, /area/station/asteroid, /area/misc/asteroid, /area/station/command/secure_bunker,
							/area/station/cargo/power_station, /area/station/engineering/power_station, /area/station/science/power_station,
							/area/station/science/power_station, /area/station/security/power_station, /area/station/service/power_station,
							/area/station/medical/aslyum, /area/station/medical/virology/isolation, /area/graveyard/tunnels, /area/graveyard/bunker,
						)
