// Modular PDA spawn themes
#define PDA_THEME_NTOS "ntos"
#define PDA_THEME_DARK_MODE "ntos_darkmode"
#define PDA_THEME_LIGHT_MODE "ntos_lightmode"
#define PDA_THEME_CAT "ntos_cat"
#define PDA_THEME_RETRO "ntOS95"
#define PDA_THEME_SYNTH "ntos_synth"
#define PDA_THEME_SPOOKY "ntos_spooky"
#define PDA_THEME_TERMINAL "ntos_terminal"

#define PDA_THEME_TITLE_NTOS "ntOS"
#define PDA_THEME_TITLE_DARK_MODE "Dark Mode"
#define PDA_THEME_TITLE_LIGHT_MODE "Light Mode"
#define PDA_THEME_TITLE_CAT "Kitty"
#define PDA_THEME_TITLE_RETRO "ntOS95"
#define PDA_THEME_TITLE_SYNTH "Synthwave"
#define PDA_THEME_TITLE_SPOOKY "Eldritch"
#define PDA_THEME_TITLE_TERMINAL "Terminal"

GLOBAL_LIST_INIT(pda_themes, list(
	PDA_THEME_TITLE_NTOS = PDA_THEME_NTOS, 
	PDA_THEME_TITLE_DARK_MODE = PDA_THEME_DARK_MODE, 
	PDA_THEME_TITLE_LIGHT_MODE = PDA_THEME_LIGHT_MODE, 
	PDA_THEME_TITLE_CAT = PDA_THEME_CAT, 
	PDA_THEME_TITLE_RETRO = PDA_THEME_RETRO, 
	PDA_THEME_TITLE_SYNTH = PDA_THEME_SYNTH, 
	PDA_THEME_TITLE_SPOOKY = PDA_THEME_SPOOKY, 
	PDA_THEME_TITLE_TERMINAL = PDA_THEME_TERMINAL
	))
