#define ZTRAIT_JUNGLE_RUINS "Jungle Ruins"
#define ZTRAIT_DAYNIGHT_CYCLE "Daynight Cycle"


#define ZTRAITS_JUNGLELAND list(\
    ZTRAIT_MINING = TRUE, \
    ZTRAIT_BOMBCAP_MULTIPLIER = 2.5, \
	ZTRAIT_ACIDRAIN = TRUE, \
	ZTRAIT_JUNGLE_RUINS = TRUE, \
	ZTRAIT_DAYNIGHT_CYCLE = TRUE, \
    ZTRAIT_BASETURF = /turf/open/water/toxic_pit)

