//Endgame Results
#define GANG_LOSS 6
#define GANG_TAKEOVER 7
#define INFILTRATION_ALLCOMPLETE 25
#define INFILTRATION_MOSTCOMPLETE 26
#define INFILTRATION_SOMECOMPLETE 27
#define INFILTRATION_NONECOMPLETE 28 
