//VOX PATHS
#define VOX_MASK_FILE 'icons/mob/clothing/species/vox/mask.dmi'
#define VOX_HEAD_FILE 'icons/mob/clothing/species/vox/head.dmi'
#define VOX_BACK_FILE 'icons/mob/clothing/species/vox/back.dmi'
#define VOX_EARS_FILE 'icons/mob/clothing/species/vox/ears.dmi'
#define VOX_EYES_FILE 'icons/mob/clothing/species/vox/eyes.dmi'
#define VOX_SHOES_FILE 'icons/mob/clothing/species/vox/shoes.dmi'
#define VOX_GLOVES_FILE 'icons/mob/clothing/species/vox/gloves.dmi'
#define VOX_HELMET_FILE 'icons/mob/clothing/species/vox/helmet.dmi'
#define VOX_SUIT_FILE 'icons/mob/clothing/species/vox/suit.dmi'
#define VOX_UNIFORM_FILE 'icons/mob/clothing/species/vox/uniform.dmi'
