/obj/machinery/vending/wardrobe/jani_wardrobe
	products = list(/obj/item/clothing/under/rank/janitor = 2,
					/obj/item/clothing/under/yogs/casualjanitorsuit = 2,
					/obj/item/clothing/suit/yogs/janitorcoat = 2,
					/obj/item/cartridge/janitor = 2,
					/obj/item/clothing/gloves/color/black = 2,
					/obj/item/clothing/head/soft/purple = 2,
					/obj/item/paint/paint_remover = 2,
					/obj/item/melee/flyswatter = 2,
					/obj/item/flashlight = 2,
					/obj/item/caution = 6,
					/obj/item/holosign_creator = 2,
					/obj/item/lightreplacer = 2,
					/obj/item/soap/nanotrasen = 2,
					/obj/item/storage/bag/trash = 2,
					/obj/item/clothing/shoes/galoshes = 2,
					/obj/item/watertank/janitor = 2,
					/obj/item/storage/belt/janitor = 2)

/obj/machinery/vending/wardrobe/law_wardrobe
	products = list(/obj/item/clothing/under/lawyer/female = 2,
					/obj/item/clothing/under/lawyer/black = 2,
					/obj/item/clothing/under/lawyer/red = 2,
					/obj/item/clothing/under/lawyer/bluesuit = 2,
					/obj/item/clothing/suit/toggle/lawyer = 2,
					/obj/item/clothing/under/lawyer/purpsuit = 2,
					/obj/item/clothing/suit/toggle/lawyer/purple = 2,
					/obj/item/clothing/under/lawyer/blacksuit = 2,
					/obj/item/clothing/suit/toggle/lawyer/black = 2,
					/obj/item/clothing/shoes/laceup = 2,
					/obj/item/clothing/accessory/lawyers_badge = 2)

/obj/machinery/vending/wardrobe/chap_wardrobe
	products = list(/obj/item/choice_beacon/holy = 1,
					/obj/item/storage/backpack/cultpack = 1,
					/obj/item/clothing/accessory/pocketprotector/cosmetology = 1,
					/obj/item/clothing/under/rank/chaplain = 1,
					/obj/item/clothing/shoes/sneakers/black = 1,
					/obj/item/clothing/suit/nun = 1,
					/obj/item/clothing/head/nun_hood = 1,
					/obj/item/clothing/suit/holidaypriest = 1,
					/obj/item/clothing/suit/yogs/witchhuntblue = 1,
					/obj/item/clothing/under/yogs/fiendsuit = 1,
					/obj/item/clothing/suit/hooded/fiendcowl = 1,
					/obj/item/clothing/under/yogs/caretaker = 1,
					/obj/item/clothing/suit/hooded/caretakercloak = 1,
					/obj/item/clothing/suit/yogs/monkrobes = 1,
					/obj/item/storage/fancy/candle_box = 2)

/obj/machinery/vending/wardrobe/robo_wardrobe
	products = list(/obj/item/clothing/glasses/hud/diagnostic = 2,
					/obj/item/clothing/head/welding/carp = 1,
					/obj/item/clothing/head/welding/fancy = 1,
					/obj/item/clothing/head/welding/demon = 1,
					/obj/item/clothing/under/rank/roboticist = 2,
					/obj/item/clothing/suit/toggle/labcoat = 2,
					/obj/item/clothing/suit/toggle/labcoat/wardtlab = 2,
					/obj/item/clothing/suit/toggle/labcoat/aeneasrinil = 2,
					/obj/item/clothing/shoes/sneakers/black = 2,
					/obj/item/clothing/gloves/fingerless = 2,
					/obj/item/clothing/head/soft/black = 2,
					/obj/item/clothing/mask/bandana/skull = 2)

/obj/machinery/vending/wardrobe/curator_wardrobe
	products = list(/obj/item/pen = 4,
					/obj/item/pen/red = 2,
					/obj/item/pen/blue = 2,
					/obj/item/pen/fourcolor = 1,
					/obj/item/pen/fountain = 2,
					/obj/item/clothing/accessory/pocketprotector = 2,
					/obj/item/storage/backpack/satchel/explorer = 1,
					/obj/item/clothing/under/yogs/treasure = 1,
					/obj/item/clothing/under/yogs/colony = 1,
					/obj/item/clothing/glasses/regular = 2,
					/obj/item/clothing/glasses/regular/jamjar = 1,
					/obj/item/storage/bag/books = 1)

/obj/machinery/vending/wardrobe/sec_wardrobe
	products = list(/obj/item/clothing/suit/hooded/wintercoat/security = 3,
					/obj/item/storage/backpack/security = 3,
					/obj/item/storage/backpack/satchel/sec = 3,
					/obj/item/storage/backpack/duffelbag/sec = 3,
					/obj/item/clothing/under/rank/security = 3,
					/obj/item/clothing/under/yogs/armyuniform = 3,
					/obj/item/clothing/shoes/jackboots = 3,
					/obj/item/clothing/head/beret/sec = 3,
					/obj/item/clothing/head/beret/corpsec = 3,
					/obj/item/clothing/head/soft/sec = 3,
					/obj/item/clothing/mask/bandana/red = 3,
					/obj/item/clothing/suit/armor/vest/secmiljacket = 3,
					/obj/item/clothing/shoes/yogs/namboots = 5,
					/obj/item/clothing/under/yogs/namjumpsuit = 5,
					/obj/item/clothing/suit/armor/vest/namflakjacket = 5,
					/obj/item/clothing/head/helmet/namhelm = 5,
					/obj/item/clothing/under/yogs/redcoatuniform = 5,
					/obj/item/clothing/suit/armor/vest/redcoatcoat = 5,
					/obj/item/clothing/head/yogs/tricornhat = 5,
					/obj/item/clothing/under/rank/security/skirt = 3,
					/obj/item/clothing/under/rank/security/grey = 3,
					/obj/item/clothing/under/yogs/shitcurity = 3,
					/obj/item/clothing/under/pants/khaki = 3,
					/obj/item/clothing/under/rank/security/blueshirt = 3)

/obj/machinery/vending/wardrobe/medi_wardrobe
	products = list(/obj/item/clothing/accessory/pocketprotector = 4,
					/obj/item/storage/backpack/duffelbag/med = 4,
					/obj/item/storage/backpack/medic = 4,
					/obj/item/storage/backpack/satchel/med = 4,
					/obj/item/clothing/head/beret/med = 4,
					/obj/item/clothing/suit/hooded/wintercoat/medical = 4,
					/obj/item/clothing/under/rank/nursesuit = 4,
					/obj/item/clothing/head/nursehat = 4,
					/obj/item/clothing/under/yogs/nursedress = 4,
					/obj/item/clothing/under/rank/medical/blue = 4,
					/obj/item/clothing/under/rank/medical/green = 4,
					/obj/item/clothing/under/rank/medical/purple = 4,
					/obj/item/clothing/under/rank/medical = 4,
					/obj/item/clothing/suit/toggle/labcoat = 4,
					/obj/item/clothing/suit/toggle/labcoat/emt = 4,
					/obj/item/clothing/shoes/sneakers/white = 4,
					/obj/item/clothing/head/soft/emt = 4,
					/obj/item/clothing/suit/apron/surgical = 4,
					/obj/item/clothing/mask/surgical = 4)

/obj/machinery/vending/wardrobe/law_wardrobe
	products = list(/obj/item/clothing/under/lawyer/female = 1,
					/obj/item/clothing/under/lawyer/black = 1,
					/obj/item/clothing/under/lawyer/red = 1,
					/obj/item/clothing/under/yogs/prosecutorsuit = 1,
					/obj/item/clothing/under/lawyer/bluesuit = 1,
					/obj/item/clothing/suit/toggle/lawyer = 1,
					/obj/item/clothing/under/lawyer/purpsuit = 1,
					/obj/item/clothing/suit/toggle/lawyer/purple = 1,
					/obj/item/clothing/under/lawyer/blacksuit = 1,
					/obj/item/clothing/suit/toggle/lawyer/black = 1,
					/obj/item/clothing/shoes/laceup = 2,
					/obj/item/clothing/accessory/lawyers_badge = 2)

/obj/machinery/vending/wardrobe/hydro_wardrobe
	products = list(/obj/item/storage/backpack/botany = 2,
					/obj/item/storage/backpack/satchel/hyd = 2,
					/obj/item/clothing/suit/hooded/wintercoat/hydro = 2,
					/obj/item/clothing/suit/apron = 2,
					/obj/item/clothing/suit/apron/overalls = 3,
					/obj/item/clothing/under/yogs/botanyuniform = 3,
					/obj/item/clothing/under/rank/hydroponics = 3,
					/obj/item/clothing/mask/bandana = 3,
					/obj/item/clothing/accessory/armband/hydro = 3)

/obj/machinery/vending/wardrobe/bar_wardrobe
	products = list(/obj/item/clothing/head/that = 2,
					/obj/item/radio/headset/headset_srv = 2,
					/obj/item/clothing/under/sl_suit = 2,
					/obj/item/clothing/under/rank/bartender = 2,
					/obj/item/clothing/under/yogs/billydonka = 2,
					/obj/item/clothing/head/yogs/billydonkahat = 2,
					/obj/item/cane = 2,
					/obj/item/clothing/under/yogs/callumsuit = 2,
					/obj/item/clothing/under/rank/bartender/purple = 2,
					/obj/item/clothing/accessory/waistcoat = 2,
					/obj/item/clothing/suit/apron/purple_bartender = 2,
					/obj/item/clothing/head/soft/black = 2,
					/obj/item/clothing/shoes/sneakers/black = 2,
					/obj/item/reagent_containers/glass/rag = 2,
					/obj/item/storage/box/beanbag = 1,
					/obj/item/clothing/suit/armor/vest/alt = 1,
					/obj/item/circuitboard/machine/dish_drive = 1,
					/obj/item/clothing/glasses/sunglasses/reagent = 1,
					/obj/item/storage/belt/bandolier = 1)

/obj/machinery/vending/wardrobe/science_wardrobe
	products = list(/obj/item/clothing/accessory/pocketprotector = 3,
					/obj/item/storage/backpack/science = 3,
					/obj/item/storage/backpack/satchel/tox = 3,
					/obj/item/clothing/head/beret/sci = 3,
					/obj/item/clothing/suit/hooded/wintercoat/science = 3,
					/obj/item/clothing/under/rank/scientist = 3,
					/obj/item/clothing/suit/toggle/labcoat/science = 3,
					/obj/item/clothing/shoes/sneakers/white = 3,
					/obj/item/radio/headset/headset_sci = 3,
					/obj/item/clothing/mask/gas = 3)

/obj/machinery/vending/wardrobe/atmos_wardrobe
	products = list(/obj/item/clothing/accessory/pocketprotector = 2,
					/obj/item/storage/backpack/duffelbag/engineering = 2,
					/obj/item/storage/backpack/satchel/eng = 2,
					/obj/item/storage/backpack/industrial = 2,
					/obj/item/clothing/suit/hooded/wintercoat/engineering/atmos = 3,
					/obj/item/clothing/head/beret/atmos = 3,
					/obj/item/clothing/under/rank/atmospheric_technician = 3,
					/obj/item/clothing/shoes/sneakers/black = 3)

/obj/machinery/vending/wardrobe/engi_wardrobe
	products = list(/obj/item/clothing/accessory/pocketprotector = 3,
					/obj/item/storage/backpack/duffelbag/engineering = 3,
					/obj/item/storage/backpack/industrial = 3,
					/obj/item/storage/backpack/satchel/eng = 3,
					/obj/item/clothing/suit/hooded/wintercoat/engineering = 3,
					/obj/item/clothing/under/rank/engineer = 3,
					/obj/item/clothing/under/rank/engineer/hazard = 3,
					/obj/item/clothing/suit/hazardvest = 3,
					/obj/item/clothing/shoes/workboots = 3,
					/obj/item/clothing/head/beret/eng = 3,
					/obj/item/clothing/head/hardhat = 3,
					/obj/item/clothing/head/welding/demon = 1,
					/obj/item/clothing/head/welding/knight = 1,
					/obj/item/clothing/head/welding/engie = 1,
					/obj/item/clothing/head/hardhat/weldhat = 1)