/proc/log_mentor(text)
	GLOB.mentorlog.Add(text)
	WRITE_LOG(GLOB.world_game_log, "MENTOR: [text]")
/proc/log_looc(text)
	if (CONFIG_GET(flag/log_looc))
		WRITE_LOG(GLOB.world_game_log, "LOOC: [text]")
/proc/log_tochat(text)
	if (CONFIG_GET(flag/log_tochat))
		WRITE_LOG(GLOB.world_tochat_log, "TOCHAT: [text]")