#define JOB_MODIFICATION_MAP_NAME "Redoubt"

MAP_REMOVE_JOB(clerk) //YOGS start - yogjobs
MAP_REMOVE_JOB(paramedic)
MAP_REMOVE_JOB(psych)
MAP_REMOVE_JOB(signal_tech)
MAP_REMOVE_JOB(miningmedic) //YOGS end - yogjobs
MAP_REMOVE_JOB(ai)
MAP_REMOVE_JOB(atmos)
MAP_REMOVE_JOB(bartender)
MAP_REMOVE_JOB(hydro)
MAP_REMOVE_JOB(cargo_tech)
MAP_REMOVE_JOB(chaplain)
MAP_REMOVE_JOB(chemist)
MAP_REMOVE_JOB(chief_engineer)
MAP_REMOVE_JOB(cmo)
MAP_REMOVE_JOB(clown)
MAP_REMOVE_JOB(cook)
MAP_REMOVE_JOB(curator)
MAP_REMOVE_JOB(cyborg)
MAP_REMOVE_JOB(detective)
MAP_REMOVE_JOB(geneticist)
MAP_REMOVE_JOB(janitor)
MAP_REMOVE_JOB(lawyer)
MAP_REMOVE_JOB(mime)
MAP_REMOVE_JOB(rd)
MAP_REMOVE_JOB(roboticist)
MAP_REMOVE_JOB(officer)
MAP_REMOVE_JOB(mining)
MAP_REMOVE_JOB(engineer)
MAP_REMOVE_JOB(virologist)